# Generated by Django 4.2.7 on 2024-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_titleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first',
            field=models.TextField(default='Default first text'),
        ),
        migrations.AddField(
            model_name='post',
            name='firstImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='second',
            field=models.TextField(default='Default second text'),
        ),
        migrations.AddField(
            model_name='post',
            name='secondImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
